### Two new Users 
post http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Firefly",
    "name" : "Pope",
    "password": "Serenity"
}

###
post http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "theOne",
    "name" : "Neo",
    "password": "Simulca"
}

###
post http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Edmnin",
    "name" : "Smow",
    "password": "RShA"
}

### post a blog
post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Dijsktra's ",
    "url": "dijsktraalgorithm.com",
    "likes": 4,
    "userId": "6144615c0ecd6b2601bffb58"
}

### post a blog
post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Firefly ",
    "url": "dijsktrafgalgorithm.com",
    "likes": 4,
    "author": "new author",
    "userId": "614459d566886a26628f459b"
}

### get notes
get http://localhost:3003/api/blogs

###
post http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "do",
    "name" : "Smow",
    "password": "r"
}

### correct login
post http://localhost:3003/api/login 
Content-Type: application/json

{
            "username": "Firefly",
          "password": "Serenity"
          }

### delete user 
DELETE http://localhost:3003/api/users/614461400ecd6b2601bffb54

### Send blog with logged in user
post http://localhost:3003/api/login
Content-Type: application/json

{
        "username": "Firefly",
        "password": "Serenity"
      }
###
post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZpcmVmbHkiLCJpZCI6IjYxNDQ1OWQ1NjY4ODZhMjY2MjhmNDU5YiIsImlhdCI6MTYzMTk0MjczM30.eSDRcOMgTYFigpDYNUOM90CfZwymuMgRheLCeicK_uE 

{
        "username": "Firefly",
        "password": "Serenity",
          "title": "The Civil 52",
          "author": "Pope",
          "url": "outlander.com",
          "likes": 34
      }

### 'Firefly' delete blog
delete http://localhost:3003/api/blogs/6145021ba70c238d9a183ca0
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZpcmVmbHkiLCJpZCI6IjYxNDQ1OWQ1NjY4ODZhMjY2MjhmNDU5YiIsImlhdCI6MTYzMjAxMTE2MywiZXhwIjoxNjMyMDE0NzYzfQ.PaCN-n8tpEYzd6fFx7vxOxiZJEXkjDtKrJK9PwQ8Gbc
